---
- shell: "docker inspect -f '{% raw %}{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}{% endraw %}' sdn_router_1"
  register: sdn_router_1_ip

- shell: "docker inspect -f '{% raw %}{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}{% endraw %}' sdn_controller_1"
  register: sdn_controller_1_ip

- name: create config
  template:
    src: global.conf.j2
    dest: "{{ config_path }}/global.conf"





