---
- name: Install python3-dev
  apt:
    name: python3-dev
    state: present
  become: true

- name: Install virtualenv
  pip:
    name: virtualenv
    state: present
  become: true

- name: Install requirements
  pip:
    requirements: '{{ item }}'
    virtualenv: '{{ warsztaty_path }}/sdn_venv'
    virtualenv_python: python3.6
  with_items:
    - '{{ warsztaty_path }}/requirements_base.txt'
    - '{{ warsztaty_path }}/robot-tests/requirements.txt'
    - '{{ warsztaty_path }}/sdn/agent/requirements.txt'
    - '{{ warsztaty_path }}/sdn/controller/requirements.txt'
    - '{{ warsztaty_path }}/sdn/router/requirements.txt'
  become: true

